name: prefect-n2v
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - cudatoolkit=11.2.*
  - pip
  - pip:
    - nvidia-cudnn-cu11==8.6.0.163
    - tensorflow==2.10.*
    - n2v==0.3.2
    - prefect==2.9.*
    - git+https://github.com/fmi-faim/custom-prefect-result@v0.1.8
    - git+https://github.com/fmi-faim/faim-prefect@v0.2.2
    - wandb
